"""HousePredModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNfnW7ctwekWae8e8WVEieTJsoF0_Pk4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

file_path = "/content/Housing.csv"
df = pd.read_csv(file_path)
df.head()

categorical_cols = df.select_dtypes(include=['object']).columns
df_processed = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
print(f"Original shape: {df.shape}")
print(f"Processed shape: {df_processed.shape}")
print("First 5 rows of the processed DataFrame:")
print(df_processed.head())

coefficients = model_lr.coef_
intercept = model_lr.intercept_

# Get feature names from X (training data)
feature_names = X.columns

# Construct the equation string
equation = f"y = {intercept:.2f}"
for i, coeff in enumerate(coefficients):
    equation += f" + ({coeff:.2f} * {feature_names[i]})"

print("Linear Regression Equation:")
print(equation)

print("Linear Regression Coefficients (Beta Values):")
for feature, coeff in zip(X.columns, model_lr.coef_):
    print(f"{feature}: {coeff:.2f}")
print(f"Intercept: {model_lr.intercept_:.2f}")

y = df_processed['price']
X = df_processed.drop('price', axis=1)

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")
print("First 5 rows of X:")
print(X.head())

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

X_train_np = X_train.to_numpy()
y_train_np = y_train.to_numpy().reshape(-1, 1)

# Add a bias (intercept) term to X_train
X_train_b = np.c_[np.ones((X_train_np.shape[0], 1)), X_train_np]

# Initialize parameters
theta = np.random.randn(X_train_b.shape[1], 1) # Random initialization

learning_rate = 0.0000000001 # A very small learning rate due to large feature values
n_iterations = 1000

m = len(X_train_b)

# SGD implementation
for iteration in range(n_iterations):
    # Randomly pick one instance
    random_index = np.random.randint(m)
    xi = X_train_b[random_index:random_index+1]
    yi = y_train_np[random_index:random_index+1]

    # Calculate gradient for this single instance
    gradients = 2 * xi.T.dot(xi.dot(theta) - yi)

    # Update parameters
    theta = theta - learning_rate * gradients

print("SGD optimized coefficients (including intercept):")
print(theta)

# To compare with scikit-learn's Linear Regression coefficients (without intercept for features)
# Note: The learning rate and number of iterations for SGD are simplified for demonstration
# and would typically require careful tuning.
print("\nScikit-learn Linear Regression Coefficients (from earlier training):")
for feature, coeff in zip(['Intercept'] + list(X.columns), [model_lr.intercept_] + list(model_lr.coef_)):
    print(f"{feature}: {coeff:.2f}")

model_lr = LinearRegression()
model_lr.fit(X_train, y_train)
y_pred_lr = model_lr.predict(X_test)

print("Linear Regression model trained and predictions made.")

"""### Visualizing Optimizer Convergence

Let's plot the Mean Squared Error (MSE) over iterations/epochs for both Stochastic Gradient Descent (SGD) and Mini-Batch Gradient Descent (MBGD) to visually compare their convergence paths.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(range(len(cost_history_sgd)), cost_history_sgd, label='Stochastic Gradient Descent (SGD)')
plt.plot(range(len(cost_history_mbgd)), cost_history_mbgd, label='Mini-Batch Gradient Descent (MBGD)')
plt.xlabel('Iterations (SGD) / Epochs (MBGD)')
plt.ylabel('Mean Squared Error (MSE)')
plt.title('Optimizer Convergence: MSE over Iterations/Epochs')
plt.legend()
plt.grid(True)
plt.yscale('log') # Use a logarithmic scale for better visualization if MSE values vary widely
plt.show()

"""### Visualizing Optimizer Convergence

Let's plot the Mean Squared Error (MSE) over iterations/epochs for both Stochastic Gradient Descent (SGD) and Mini-Batch Gradient Descent (MBGD) to visually compare their convergence paths.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(range(len(cost_history_sgd)), cost_history_sgd, label='Stochastic Gradient Descent (SGD)')
plt.plot(range(len(cost_history_mbgd)), cost_history_mbgd, label='Mini-Batch Gradient Descent (MBGD)')
plt.xlabel('Iterations (SGD) / Epochs (MBGD)')
plt.ylabel('Mean Squared Error (MSE)')
plt.title('Optimizer Convergence: MSE over Iterations/Epochs')
plt.legend()
plt.grid(True)
plt.yscale('log') # Use a logarithmic scale for better visualization if MSE values vary widely
plt.show()

"""### Mini-Batch Stochastic Gradient Descent Implementation

Mini-Batch Gradient Descent (MBGD) is a variation of the Gradient Descent algorithm that splits the training dataset into small batches. It computes the gradient and updates the model parameters for each mini-batch. This approach strikes a balance between pure Stochastic Gradient Descent (which uses one sample) and Batch Gradient Descent (which uses the entire dataset), offering faster convergence than BGD and more stable updates than SGD.

We will implement MBGD with a batch size of 64.
"""

# Reuse X_train_b and y_train_np from the previous SGD setup
# X_train_np = X_train.to_numpy()
# y_train_np = y_train.to_numpy().reshape(-1, 1)
# X_train_b = np.c_[np.ones((X_train_np.shape[0], 1)), X_train_np]
from sklearn.metrics import mean_squared_error # Ensure mean_squared_error is imported

# Initialize parameters for Mini-Batch SGD
theta_mbgd = np.random.randn(X_train_b.shape[1], 1) # Random initialization

learning_rate_mbgd = 0.0000000001 # A small learning rate, similar to SGD
n_epochs = 1000 # Number of passes over the entire training dataset
batch_size = 64

m = len(X_train_b)
n_batches = int(np.ceil(m / batch_size))

cost_history_mbgd = [] # To store MSE at the end of each epoch

# Mini-Batch SGD implementation
for epoch in range(n_epochs):
    # Shuffle the data at the beginning of each epoch
    shuffled_indices = np.random.permutation(m)
    X_shuffled = X_train_b[shuffled_indices]
    y_shuffled = y_train_np[shuffled_indices]

    for i in range(n_batches):
        # Get the current mini-batch
        start_idx = i * batch_size
        end_idx = min(start_idx + batch_size, m)
        xi_batch = X_shuffled[start_idx:end_idx]
        yi_batch = y_shuffled[start_idx:end_idx]

        # Calculate gradient for this mini-batch
        gradients_mbgd = 2 * xi_batch.T.dot(xi_batch.dot(theta_mbgd) - yi_batch) / len(xi_batch)

        # Update parameters
        theta_mbgd = theta_mbgd - learning_rate_mbgd * gradients_mbgd

    # Calculate MSE on the full training set at the end of each epoch
    y_pred_train_mbgd = X_train_b.dot(theta_mbgd)
    mse_train_mbgd = mean_squared_error(y_train_np, y_pred_train_mbgd)
    cost_history_mbgd.append(mse_train_mbgd)

print(f"Mini-Batch SGD optimized coefficients (batch size={batch_size}, including intercept):")
print(theta_mbgd)

# To compare with scikit-learn's Linear Regression coefficients
print("\nScikit-learn Linear Regression Coefficients (from earlier training):")
# Ensure model_lr is available from previous steps
print(f"Intercept: {model_lr.intercept_:.2f}")
for feature, coeff in zip(X.columns, model_lr.coef_):
    print(f"{feature}: {coeff:.2f}")

"""### Corrected Code Execution Flow for Linear Regression and SGD"""

# 1. Separate target variable (y) from features (X)
y = df_processed['price']
X = df_processed.drop('price', axis=1)

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")
print("First 5 rows of X:")
print(X.head())

# 2. Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

# 3. Define and train the Linear Regression model (model_lr)
model_lr = LinearRegression()
model_lr.fit(X_train, y_train)
y_pred_lr = model_lr.predict(X_test)

print("Linear Regression model trained and predictions made.")

# 4. Display Linear Regression Coefficients
print("Linear Regression Coefficients (Beta Values):")
for feature, coeff in zip(X.columns, model_lr.coef_):
    print(f"{feature}: {coeff:.2f}")
print(f"Intercept: {model_lr.intercept_:.2f}")

# 4. Construct and display the Linear Regression Equation
coefficients = model_lr.coef_
intercept = model_lr.intercept_
feature_names = X.columns

equation = f"y = {intercept:.2f}"
for i, coeff in enumerate(coefficients):
    equation += f" + ({coeff:.2f} * {feature_names[i]})"

print("Linear Regression Equation:")
print(equation)

"""### Stochastic Gradient Descent (SGD) Implementation"""

# 5. SGD Implementation and Comparison
from sklearn.metrics import mean_squared_error # Ensure mean_squared_error is imported

X_train_np = X_train.to_numpy()
y_train_np = y_train.to_numpy().reshape(-1, 1)

# Add a bias (intercept) term to X_train
X_train_b = np.c_[np.ones((X_train_np.shape[0], 1)), X_train_np]

# Initialize parameters
theta = np.random.randn(X_train_b.shape[1], 1) # Random initialization

# A very small learning rate due to large feature values
# (This often requires careful tuning for practical applications)
learning_rate = 0.0000000001
n_iterations = 1000

m = len(X_train_b)

cost_history_sgd = [] # To store MSE at each iteration

# SGD implementation
for iteration in range(n_iterations):
    # Randomly pick one instance
    random_index = np.random.randint(m)
    xi = X_train_b[random_index:random_index+1]
    yi = y_train_np[random_index:random_index+1]

    # Calculate gradient for this single instance
    gradients = 2 * xi.T.dot(xi.dot(theta) - yi)

    # Update parameters
    theta = theta - learning_rate * gradients

    # Calculate MSE on the full training set after each update
    y_pred_train_sgd = X_train_b.dot(theta)
    mse_train_sgd = mean_squared_error(y_train_np, y_pred_train_sgd)
    cost_history_sgd.append(mse_train_sgd)

print("SGD optimized coefficients (including intercept):")
print(theta)

# To compare with scikit-learn's Linear Regression coefficients
print("\nScikit-learn Linear Regression Coefficients (from earlier training):")
# Ensure model_lr is available from previous steps
print(f"Intercept: {model_lr.intercept_:.2f}")
for feature, coeff in zip(X.columns, model_lr.coef_):
    print(f"{feature}: {coeff:.2f}")

"""### Evaluation Graph: Comparing Model Performance"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Prepare data for plotting
metrics = {
    'Model': ['Linear Regression', 'Custom SGD', 'Custom Mini-Batch SGD', 'Huber Regressor'],
    'MSE': [mse_lr, mse_sgd, mse_mbgd, mse_huber],
    'MAE': [mae_lr, mae_sgd, mae_mbgd, mae_huber]
}
df_metrics = pd.DataFrame(metrics)

# Create subplots for MSE and MAE
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# Plot MSE
sns.barplot(x='Model', y='MSE', hue='Model', data=df_metrics, ax=axes[0], palette='viridis', legend=False)
axes[0].set_title('Mean Squared Error (MSE) Comparison')
axes[0].set_ylabel('MSE (Lower is Better)')
axes[0].ticklabel_format(style='plain', axis='y') # Prevent scientific notation on y-axis
axes[0].set_xticklabels(axes[0].get_xticklabels(), rotation=15, ha='right')
axes[0].grid(axis='y', linestyle='--', alpha=0.7)

# Plot MAE
sns.barplot(x='Model', y='MAE', hue='Model', data=df_metrics, ax=axes[1], palette='plasma', legend=False)
axes[1].set_title('Mean Absolute Error (MAE) Comparison')
axes[1].set_ylabel('MAE (Lower is Better)')
axes[1].ticklabel_format(style='plain', axis='y') # Prevent scientific notation on y-axis
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=15, ha='right')
axes[1].grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""### Visualizing Optimizer Convergence

Let's plot the Mean Squared Error (MSE) over iterations/epochs for both Stochastic Gradient Descent (SGD) and Mini-Batch Gradient Descent (MBGD) to visually compare their convergence paths.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(range(len(cost_history_sgd)), cost_history_sgd, label='Stochastic Gradient Descent (SGD)')
plt.plot(range(len(cost_history_mbgd)), cost_history_mbgd, label='Mini-Batch Gradient Descent (MBGD)')
plt.xlabel('Iterations (SGD) / Epochs (MBGD)')
plt.ylabel('Mean Squared Error (MSE)')
plt.title('Optimizer Convergence: MSE over Iterations/Epochs')
plt.legend()
plt.grid(True)
plt.yscale('log') # Use a logarithmic scale for better visualization if MSE values vary widely
plt.show()

"""### Evaluating Custom SGD and Mini-Batch SGD Models"""

# Prepare X_test with a bias term for custom SGD/MBGD predictions
X_test_np = X_test.to_numpy()
X_test_b = np.c_[np.ones((X_test_np.shape[0], 1)), X_test_np]

# Generate predictions using SGD optimized coefficients (theta)
y_pred_sgd = X_test_b.dot(theta)

# Generate predictions using Mini-Batch SGD optimized coefficients (theta_mbgd)
y_pred_mbgd = X_test_b.dot(theta_mbgd)

print("Predictions generated using custom SGD and Mini-Batch SGD coefficients.")

from sklearn.metrics import mean_squared_error, mean_absolute_error

# Evaluate SGD Model
mse_sgd = mean_squared_error(y_test, y_pred_sgd)
mae_sgd = mean_absolute_error(y_test, y_pred_sgd)
print(f"Mean Squared Error for Custom SGD: {mse_sgd}")
print(f"Mean Absolute Error for Custom SGD: {mae_sgd}")

# Evaluate Mini-Batch SGD Model
mse_mbgd = mean_squared_error(y_test, y_pred_mbgd)
mae_mbgd = mean_absolute_error(y_test, y_pred_mbgd)
print(f"\nMean Squared Error for Custom Mini-Batch SGD: {mse_mbgd}")
print(f"Mean Absolute Error for Custom Mini-Batch SGD: {mae_mbgd}")

print("\n--- Comparison with Scikit-learn Linear Regression ---")
print(f"Mean Squared Error for Scikit-learn Linear Regression: {mse_lr}")
print(f"Mean Absolute Error for Scikit-learn Linear Regression: {mae_lr}")

"""### Visualizing Custom SGD and Mini-Batch SGD Predictions"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(20, 7), sharex=True, sharey=True)

# Plot Custom SGD Predictions
sns.scatterplot(x=y_test, y=y_pred_sgd.flatten(), alpha=0.6, ax=axes[0])
axes[0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Ideal line
axes[0].set_xlabel("Actual Prices (y_test)")
axes[0].set_ylabel("Predicted Prices (Custom SGD)")
axes[0].set_title("Custom SGD: Actual vs. Predicted Prices")
axes[0].grid(True)

# Plot Custom Mini-Batch SGD Predictions
sns.scatterplot(x=y_test, y=y_pred_mbgd.flatten(), alpha=0.6, ax=axes[1])
axes[1].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Ideal line
axes[1].set_xlabel("Actual Prices (y_test)")
axes[1].set_ylabel("Predicted Prices (Custom Mini-Batch SGD)")
axes[1].set_title("Custom Mini-Batch SGD: Actual vs. Predicted Prices")
axes[1].grid(True)

plt.tight_layout()
plt.show()

"""### Model Evaluation"""

# 6. Evaluate Linear Regression Model (MSE)
from sklearn.metrics import mean_squared_error
mse_lr = mean_squared_error(y_test, y_pred_lr)
print(f"Mean Squared Error for Linear Regression: {mse_lr}")

# 7. Train and Evaluate Huber Regressor
from sklearn.linear_model import HuberRegressor
model_huber = HuberRegressor()
model_huber.fit(X_train, y_train)
y_pred_huber = model_huber.predict(X_test)

mse_huber = mean_squared_error(y_test, y_pred_huber)
print(f"Huber Regressor model trained and predictions made.")
print(f"Mean Squared Error for Huber Regressor: {mse_huber}")

# 8. Compare Mean Absolute Error (MAE)
from sklearn.metrics import mean_absolute_error
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mae_huber = mean_absolute_error(y_test, y_pred_huber)

print(f"Mean Absolute Error for Linear Regression: {mae_lr}")
print(f"Mean Absolute Error for Huber Regressor: {mae_huber}")

# 9. Visualize Linear Regression Predictions
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred_lr, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Ideal line
plt.xlabel("Actual Prices (y_test)")
plt.ylabel("Predicted Prices (y_pred_lr)")
plt.title("Linear Regression: Actual vs. Predicted Prices")
plt.grid(True)
plt.show()

from sklearn.metrics import mean_squared_error
mse_lr = mean_squared_error(y_test, y_pred_lr)
print(f"Mean Squared Error for Linear Regression: {mse_lr}")

from sklearn.metrics import mean_absolute_error
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mae_huber = mean_absolute_error(y_test, y_pred_huber)

print(f"Mean Absolute Error for Linear Regression: {mae_lr}")
print(f"Mean Absolute Error for Huber Regressor: {mae_huber}")

from sklearn.linear_model import HuberRegressor
model_huber = HuberRegressor()
model_huber.fit(X_train, y_train)
y_pred_huber = model_huber.predict(X_test)

mse_huber = mean_squared_error(y_test, y_pred_huber)
print(f"Huber Regressor model trained and predictions made.")
print(f"Mean Squared Error for Huber Regressor: {mse_huber}")

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred_lr, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Ideal line
plt.xlabel("Actual Prices (y_test)")
plt.ylabel("Predicted Prices (y_pred_lr)")
plt.title("Linear Regression: Actual vs. Predicted Prices")
plt.grid(True)
plt.show()